name: Build project

on: push

jobs:
  gradle-build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout project
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: gradle

    - name: Run gradle build
      run: ./gradlew build